# Generated by Django 4.2.4 on 2023-08-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reply_comment_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_pic',
        ),
    ]
