# Generated by Django 4.2.4 on 2023-08-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_forbiddenword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forbiddenword',
            name='word',
        ),
        migrations.AddField(
            model_name='forbiddenword',
            name='forbidden_words',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
