# Generated by Django 4.2.4 on 2023-08-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_forbiddenword_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forbiddenword',
            name='forbidden_words',
        ),
        migrations.AddField(
            model_name='forbiddenword',
            name='word',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
