# Generated by Django 4.2.4 on 2023-08-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_forbiddenword_forbidden_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='acount',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(),
        ),
    ]
