# Generated by Django 4.2.4 on 2023-08-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post_acount_alter_author_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='acount',
            new_name='account',
        ),
    ]
